package main

type User struct {
	ID    string
	Name  string
	Email string
}

var users = []User{
	{ID: "1", Name: "John Doe", Email: "john.doe@gmail.com"},
	{ID: "2", Name: "Jane Smith", Email: "jane.smith@gmail.com"},
	{ID: "3", Name: "Alice Johnson", Email: "alice.johnson@gmail.com"},
	{ID: "4", Name: "Bob Brown", Email: "bob.brown@gmail.com"},
	{ID: "5", Name: "Charlie Davis", Email: "charlie.davis@gmail.com"},
	{ID: "6", Name: "Daisy Evans", Email: "daisy.evans@gmail.com"},
	{ID: "7", Name: "Edward Foster", Email: "edward.foster@gmail.com"},
	{ID: "8", Name: "Fiona Green", Email: "fiona.green@gmail.com"},
	{ID: "9", Name: "George Harris", Email: "george.harris@gmail.com"},
	{ID: "10", Name: "Hannah Ingram", Email: "hannah.ingram@gmail.com"},
	{ID: "11", Name: "Ian Johnson", Email: "ian.johnson@gmail.com"},
	{ID: "12", Name: "Jessica King", Email: "jessica.king@gmail.com"},
	{ID: "13", Name: "Kevin Lewis", Email: "kevin.lewis@gmail.com"},
	{ID: "14", Name: "Laura Miller", Email: "laura.miller@gmail.com"},
	{ID: "15", Name: "Michael Nelson", Email: "michael.nelson@gmail.com"},
	{ID: "16", Name: "Nina O'Connor", Email: "nina.oconnor@gmail.com"},
	{ID: "17", Name: "Oliver Parker", Email: "oliver.parker@gmail.com"},
	{ID: "18", Name: "Paul Quinn", Email: "paul.quinn@gmail.com"},
	{ID: "19", Name: "Rachel Roberts", Email: "rachel.roberts@gmail.com"},
	{ID: "20", Name: "Steve Scott", Email: "steve.scott@gmail.com"},
	{ID: "21", Name: "Tina Thompson", Email: "tina.thompson@gmail.com"},
	{ID: "22", Name: "Ursula Underwood", Email: "ursula.underwood@gmail.com"},
	{ID: "23", Name: "Victor Vargas", Email: "victor.vargas@gmail.com"},
	{ID: "24", Name: "Wendy White", Email: "wendy.white@gmail.com"},
	{ID: "25", Name: "Xander Young", Email: "xander.young@gmail.com"},
	{ID: "26", Name: "Yara Zane", Email: "yara.zane@gmail.com"},
	{ID: "27", Name: "Zoe Adams", Email: "zoe.adams@gmail.com"},
	{ID: "28", Name: "Aaron Bell", Email: "aaron.bell@gmail.com"},
	{ID: "29", Name: "Becky Carter", Email: "becky.carter@gmail.com"},
	{ID: "30", Name: "Chris Diaz", Email: "chris.diaz@gmail.com"},
	{ID: "31", Name: "Debbie Edwards", Email: "debbie.edwards@gmail.com"},
	{ID: "32", Name: "Ethan Flores", Email: "ethan.flores@gmail.com"},
	{ID: "33", Name: "Felicity Grant", Email: "felicity.grant@gmail.com"},
	{ID: "34", Name: "Gary Hill", Email: "gary.hill@gmail.com"},
	{ID: "35", Name: "Holly Ivers", Email: "holly.ivers@gmail.com"},
	{ID: "36", Name: "Isaac James", Email: "isaac.james@gmail.com"},
	{ID: "37", Name: "Jasmine Kelly", Email: "jasmine.kelly@gmail.com"},
	{ID: "38", Name: "Kyle Lewis", Email: "kyle.lewis@gmail.com"},
	{ID: "39", Name: "Liam Martinez", Email: "liam.martinez@gmail.com"},
	{ID: "40", Name: "Mia Norris", Email: "mia.norris@gmail.com"},
	{ID: "41", Name: "Nathan Owens", Email: "nathan.owens@gmail.com"},
	{ID: "42", Name: "Olivia Parker", Email: "olivia.parker@gmail.com"},
	{ID: "43", Name: "Peter Quinn", Email: "peter.quinn@gmail.com"},
	{ID: "44", Name: "Quincy Reed", Email: "quincy.reed@gmail.com"},
	{ID: "45", Name: "Rachel Smith", Email: "rachel.smith@gmail.com"},
	{ID: "46", Name: "Sam Taylor", Email: "sam.taylor@gmail.com"},
	{ID: "47", Name: "Tina Underwood", Email: "tina.underwood@gmail.com"},
	{ID: "48", Name: "Ursula Vasquez", Email: "ursula.vasquez@gmail.com"},
	{ID: "49", Name: "Victor White", Email: "victor.white@gmail.com"},
	{ID: "50", Name: "Wendy Xiong", Email: "wendy.xiong@gmail.com"},
}
